[package]
name = "taxus-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
gloo-timers = "0.4.0"
js-sys = "0.3"
postcard = { version = "1", features = [ "alloc" ] }
serde = { workspace = true }
rust-stemmers = "1.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Event", "EventTarget", "HtmlInputElement", "Node"] }
yew = "0.23"
serde-wasm-bindgen = "0.6"
