[package]
name = "taxus-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
gloo-timers = "0.4.0"
js-sys = "0.3.95"
postcard = { version = "1.1.3", features = [ "alloc" ] }
serde = { workspace = true }
rust-stemmers = "1.2.0"
wasm-bindgen = "0.2.114"
wasm-bindgen-futures = "0.4.68"
web-sys = { version = "0.3.95", features = ["Document", "Event", "EventTarget", "HtmlInputElement", "Node"] }
yew = "0.23.0"
serde-wasm-bindgen = "0.6.5"
