[package]
name = "taxus-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
taxus-common = { path = "../taxus-common" }
serde_json = "1.0.149"
wasm-bindgen = "0.2.114"
web-sys = { version = "0.3.91", features = ["console", "Document", "Window", "HtmlElement", "DomStringMap", "NodeList", "Element"] }
yew = { version = "0.23", features = [ "hydration" ] }
