[book]
authors = ["Jeffrey D. Mitchell"]
language = "en"
src = "src"
title = "Taxus Documentation"
description = "Documentation for the Taxus Static Site Generator"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://codeberg.org/crustyrustacean/taxus"
edit-url-template = "https://codeberg.org/crustyrustacean/taxus/edit/trunk/docs/{path}"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
